<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RevitVersion>2023</RevitVersion>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ParallelSystemsPlugin.2023</AssemblyName>
    <DefineConstants>$(DefineConstants);REVIT2023;REVIT2022_OR_GREATER;REVIT2023_OR_OLDER;REVIT2024_OR_EARLIER;REVIT_LEGACY_DOTNET</DefineConstants>
  </PropertyGroup>

  <Import Project="..\Build\RevitAdapter.Common.props" />
  <Import Project="..\ParallelSystemsPlugin.Shared\ParallelSystemsPlugin.Shared.projitems" Label="Shared" />
  <Import Project="..\Build\RevitAdapter.Common.targets" />
  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
